### ISSUE TITLE
Linux is unable to mount NTFS as R/W

### ISSUE THREAD

**Issue by runninghamster0** [amitxv/EVA#61]
It seems the Windows drive is mounted as read-only in Linux Mint when Fast Startup is enabled in Windows (which it is by default).

Disabling it and rebooting back into Linux Mint allowed the drive to be correctly mounted as R/W.

On a previous install I didn't have this issue, but I think the step of disabling fast startup before booting into Linux should be added just in case.

**Comment by amitxv** [comment]
Did you correctly merge the registry files in the [Merge the Registry Files](https://github.com/amitxv/EVA/blob/main/docs/post-install.md#merge-the-registry-files) step? Fast Startup should already be disabled with the following registry key as stated in [this article](https://theitbros.com/disable-fast-startup-windows/):

https://github.com/amitxv/EVA/blob/332967616dd06df0987aa9edb454819c37eb5103/prerequisites/scripts/registry/7%2B.reg#L96-L98

Another reason why i intentionally did not give the user an instruction to manually disable fast startup is because the option should not even show in control panel with the correct BIOS settings 
![image](https://user-images.githubusercontent.com/86924251/192509675-b3f865e5-1923-4791-b319-93339c18d873.png)

**Comment by runninghamster0** [comment]
> Did you correctly merge the registry files in the [Merge the Registry Files](https://github.com/amitxv/EVA/blob/main/docs/post-install.md#merge-the-registry-files) step? Fast Startup should already be disabled with the following registry key as stated in [this article](https://www.passfab.com/windows-10/disable-fast-boot-windows-10.html):
> 
> https://github.com/amitxv/EVA/blob/332967616dd06df0987aa9edb454819c37eb5103/prerequisites/scripts/registry/7%2B.reg#L86-L87
> 
> https://github.com/amitxv/EVA/blob/332967616dd06df0987aa9edb454819c37eb5103/prerequisites/scripts/registry/7%2B.reg#L96-L98
> 
> Another reason why i intentionally did not give the user an instruction to manually disable fast startup is because the option should not even show in control panel with the correct BIOS settings 
> ![image](https://user-images.githubusercontent.com/86924251/192509675-b3f865e5-1923-4791-b319-93339c18d873.png)
> 

I definitely did merge the registry and it printed done as mentioned in the instructions.

I agree with you, I don't think it should've happened. It was probably a one-off case for my device as I've followed the setup previously and didn't run into this issue.

You can close the issue, it's probably just something on my end.
Thanks for the project btw!

**Comment by amitxv** [comment]
If it happens again, consider checking the registry keys above to ensure none of them have changed, perhaps Windows may be changing them for some reason

**Comment by amitxv** [comment]
Sorry, I just noticed that the registry step is before the debloating with Linux step so fast startup is still enabled, I'm working to resolve this by changing the order but it is slightly more complicated as it seems due to the Python vcredist dependency. Will consider rewriting in another language

**Comment by amitxv** [comment]
Resolved in https://github.com/amitxv/EVA/commit/f330269acd6062cdcfafb40689392a23d5b2f65d (notice the extra step to disable fast startup)
